#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 &

if [[ $(xrandr -q | grep 'HDMI2 connected') ]]; then
	~/.local/bin/manage_workspaces.sh add
fi
~/.local/bin/startup

bspc config border_width         2
bspc config window_gap          12

bspc config -m focused top_padding 30
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle 	 true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# source the colors.
. ~/.cache/wal/colors.sh

# Set the border colors.
bspc config normal_border_color "$color15"
bspc config active_border_color "$color12"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color2"
