#!/usr/bin/env sh

function main() {
    # Pipewire
    #SOURCE=$(pw-record --list-targets | sed -n 's/^*.*"\(.*\)" prio=.*$/\1/p')
    SINK=$(pw-play --list-targets | sed -n 's/^*.*"\(.*\)" prio=.*$/\1/p')
    VOLUME=$(pactl list sinks | sed -n "/${SINK}/,/Volume/ s!^[[:space:]]\+Volume:.* \([[:digit:]]\+\)%.*!\1!p")
    IS_MUTED=$(pactl list sinks | sed -n "/${SINK}/,/Mute/ s/Mute: \(yes\)/\1/p")
    active_port=$(pactl list sinks | rg "^\s*Active Port: (\S*)$" -r '$1')

    action=$1
    if [ "${action}" == "up" ]; then
        pactl set-sink-volume @DEFAULT_SINK@ +10%
    elif [ "${action}" == "down" ]; then
        pactl set-sink-volume @DEFAULT_SINK@ -10%
    elif [ "${action}" == "mute" ]; then
        pactl set-sink-mute @DEFAULT_SINK@ toggle
    else
	case $active_port in 
            "analog-output-headphones")
                icon=""
	        ;;
            "analog-output-speaker")
                icon=""
	        ;;
            *)
                icon="?"
	esac

        if [ "${IS_MUTED}" != "" ]; then
            echo "$icon  MUTED"
        else
            echo "$icon ${VOLUME}%"
        fi
    fi
}

main $@
